### ISSUE TITLE
[SQL] JSON datatype return value and TEXT type workaround.

### ISSUE THREAD

**Issue by reedHam** [tauri-apps/plugins-workspace#112]
Hi,

Thanks for your hard work.

I am trying to use the JSON datatype in an SQLite database.

I opened a previous issue about this here https://github.com/tauri-apps/plugins-workspace/issues/93

Thanks to @FabianLars for suggesting to use a text field and preform parsing and deserialization manually.  
Works just fine but trying to use the JSON datatype was still confusing. 

SQLite supports JSON as a datatype although it is stored as text, listed in the docs here.
https://www.sqlite.org/json1.html
And when I attempted to use it with the SQL plugin I was able to store the information in the SQLite database but on retrieval a null value is returned.

If the plugin is not going to support deserialization then rather than returning NULL for JSON datatypes returning the string representation or simply an error would be better I believe.

I think that this would make it easier for a developer to apply this workaround.

**Comment by FabianLars** [comment]
> I opened a previous issue about this here https://github.com/tauri-apps/plugins-workspace/issues/93

Next time please give me more than 5 minutes to react. 😂 I was in the process of writing down my thoughts and may have re-opened it.

So until now we tried to somewhat follow the actually supported datatypes (the 5 at the top here <https://www.sqlite.org/datatype3.html>) and i could write X paragraphs about how it should stay that way since JSON is not an actual datatype, and what about all the other non-existent datatypes that work in sqlite due to its typeless nature (take a look at `3.1.1. Affinity Name Examples` in the link i send for example) and so forth...
**But** i do realize that JSON is a really "special" case here and we should at least handle it like a `TEXT` column (prior discussions/PRs always revolved around deserializing it via serde_json to have automatic nested json support which imo still should not be the plugin's responsibility, at least for sqlite)

**Comment by reedHam** [comment]
Thanks so much!
