### ISSUE TITLE
[sql] unsupported datatype: UUID

### ISSUE THREAD

**Issue by KauanCurbani** [tauri-apps/plugins-workspace#1126]
When I sent a query to my Postgres database, this error was returned, but it is common to use this type in Postgres

![image](https://github.com/tauri-apps/plugins-workspace/assets/87383246/fa285155-e5bd-4277-ba02-1c5350cf6052)
![image](https://github.com/tauri-apps/plugins-workspace/assets/87383246/4df6feb8-295d-4fd5-bd50-c0d551a59590)

**Comment by cmmartin** [comment]
I've got `unsupported datatype: NUMERIC` in postgres. Seems like there should be a quick way to add these in userland

**Comment by FabianLars** [comment]
> Seems like there should be a quick way to add these in userland

That'd be hard or impossible (at least with how the SQLx crate currently works) because the queries happen in rust so the database types have to be mapped to rust types and then to json compatible types so that they can be sent back to js. I don't think we'll ever cover all types the db supports, but you can always open an issue about a missing (if there's none already) and we can take a look.

**Comment by cmmartin** [comment]
Yeah. When I wrote that, I actually meant in rust when I said "userland". But I've since realized that's kind of silly because the whole point of this plugin is you don't have to write rust
