### ISSUE TITLE
[http][v2] JS Third-party lib with dynamic loading (can't modify it) and fetch function

### ISSUE THREAD

**Issue by xburelle** [tauri-apps/plugins-workspace#1390]
Hello,

I use a js third-party lib that make fetch requests (not from http tauri plugin, but the classic way), and I get, of course, a 403 error (Forbidden). I can't change this lib, because it loaded dynamically. 

First question  : Would it be possible and dosen't affect security or performance, if the http plugin set `window.fetch = fetch` where fetch is `import { fetch } from '@tauri-apps/plugin-http'` ?

I tried it in my app.  That seems to work but don't know why, the app is slow now (and I have "out of memory" error). 

Second question : How can I solve this issue correctly ?

**Comment by FabianLars** [comment]
> Would it be possible and dosen't affect security or performance, if the http plugin set window.fetch = fetch where fetch is import { fetch } from '@tauri-apps/plugin-http' ?

Performance will be affected because the plugin uses the IPC to communicate with the rust side which always has a performance hit.
Security will also be affected, otherwise it would also give you a 403 error and cors errors etc. Other than that, we're pretty confident in our scope approach.

The performance of the plugin can only really be improved on our side (ipc improvements etc), not in your app. You could however try something that's not relying on the ipc but that will require rust or a sidecar - thinking about a small http server that will basically act as a proxy.
