### ISSUE TITLE
[shell] Question: is it possible to use the shell plugin without needing to define command in capability?

### ISSUE THREAD

**Issue by HuakunShen** [tauri-apps/plugins-workspace#1483]
It seems like the current shell plugin can only execute shell commands pre-defined in capability file. 

Is it possible to remove all restrictions and make it possible to execute any command?

**Comment by FabianLars** [comment]
> Is it possible to remove all restrictions and make it possible to execute any command?

No, and it won't ever be. One thing we want to add at some point (we had a PR open for v1) was what we have in the fs plugin, a method in rust to extend the scope (for the js side) at runtime.

Some people use cmd.exe / bash as the command and run their actual commands as shell commands (confusing wording lol), but of course we do not recommend this, only if it's really really necessary and Rust is totally out of the question.

**Comment by nukeop** [comment]
It would be great to have a cross-platform way to execute any shell command. I was reading through the docs thinking I was missing something because I couldn't find any way to do that, which is really odd. Otherwise you have to implement a Rust wrapper to do it, but it should be a part of Tauri's native spec.

**Comment by HuakunShen** [comment]
@nukeop I made a plugin https://github.com/HuakunShen/tauri-plugin-shellx
It allows executing any command.
