### ISSUE TITLE
[localhost] `window.localStorage` is wiped when quitting the application

### ISSUE THREAD

**Issue by elanzini** [tauri-apps/plugins-workspace#154]
I have integrated this plugin into my application but now every time I quit the application and restart it, the `window.localStorage` is wiped.
This is a different behavior compared to the application without the plugin.

Is this expected? Is there a way to persist the `window.localStorage`?

**Comment by FabianLars** [comment]
localStorage is bound to the origin (url), and the port is part of that. So you have 2 options:
1) Specify a static port instead of using portpicker and pray that it works on every system
2) Use an alternative to localStorage, like our [store plugin](https://github.com/tauri-apps/tauri-plugin-store)

**Comment by elanzini** [comment]
Thanks @FabianLars - sounds like option 2 is the preferred option 😁
