### ISSUE TITLE
[bug] [log] logDir is different as it said

### ISSUE THREAD

**Issue by BTMuli** [tauri-apps/plugins-workspace#1605]
From code,the `TargetKind::LogDir` in `windows` refer to 
`{configDir}/{bundleIdentifier}`，such as `C:\Users\Alice\AppData\Roaming\com. tauri. dev`

And I use `await path.appConfigDir()` in js frontend it also returns `AppData\Roaming\{identifier}`

However,I found that the log file was created in `AppData\Local\{identifier}` in fact where is appCacheDir

It occurs after I migrate tauri to v2,is there any changed?

**Comment by FabianLars** [comment]
Tauri's `app_log_dir` function was fixed in v2, so the location changed too. Compare [v2](https://docs.rs/tauri/2.0.0-beta/tauri/path/struct.PathResolver.html#method.app_log_dir) and [v1](https://docs.rs/tauri/latest/tauri/api/path/fn.app_log_dir.html)

We didn't update the plugin's docs for that though (arguably it should have been updated to mention `app_log_dir` ages ago, then this wouldn't have happened).
