### ISSUE TITLE
[log] Some feedback and confusion after trying use this plugin

### ISSUE THREAD

**Issue by percy507** [tauri-apps/plugins-workspace#171]
1. **How can I make log from tauri-rust-end?** It seems this plugin only for front-end's log. I try to re-export `log` module inside tauri-plugin-log, but not work.😭

2. When using `with_colors`, the log file and the FE `console.log` appears the color code which is unwanted.
  - console.log
    <img width="517" alt="image" src="https://user-images.githubusercontent.com/18365078/163712245-91ba526f-9cf3-48d1-8250-c79bd312d554.png">
  - log file
    <img width="454" alt="image" src="https://user-images.githubusercontent.com/18365078/163712286-a9e6f729-437d-4391-86e9-a1a1e42ae683.png">
  - terminal
    <img width="394" alt="image" src="https://user-images.githubusercontent.com/18365078/163712309-2c60324d-56fb-4af9-bf83-14681f1a5ce3.png">

3. Check the log message, the log from FE but why the target shows `tauri-plugin-log`? 

4. Why the terminal show logs from `tao` package?

    <img width="865" alt="image" src="https://user-images.githubusercontent.com/18365078/163712535-ded47e12-28fe-49b1-8584-8ed3487d5f7a.png">

```rs
// here is my config of using this plugin
.plugin(
  LoggerBuilder::new()
    .rotation_strategy(RotationStrategy::KeepAll)
    .max_file_size(4000)
    .targets([LogTarget::LogDir, LogTarget::Stdout, LogTarget::Webview])
    // .filter(|meta| meta.target().eq("tauri_plugin_log"))
    .with_colors(ColoredLevelConfig {
      error: Color::Red,
      warn: Color::Yellow,
      debug: Color::White,
      info: Color::BrightGreen,
      trace: Color::Cyan,
    })
    .build(),
)
```

**Comment by JonasKruckenberg** [comment]
> 1. **How can I make log from tauri-rust-end?** It seems this plugin only for front-end's log. I try to re-export `log` module inside tauri-plugin-log, but not work.😭

The way rusts logging system works, you can just add the `log` crate as a dependency. See 4. for more on this.




> 2. When using `with_colors`, the log file and the FE `console.log` appears the color code which is unwanted.

I agree this is a bit annoying, it's not really easy to get rid if these codes since all LogTargets share one stream of messages, but maybe we can find a solution for this regardless.

> 3. Check the log message, the log from FE but why the target shows `tauri-plugin-log`? 

That's where we *technically* produce the logs from the frontend (rusts logging system has obviously no idea about JavaScript stuff). This is something we can change very easily though 👍🏻

> 4. Why the terminal show logs from `tao` package?

The way rusts logging system works is quite ingenious, any crate can depend on `log` and the exported logging macros to produce logging messages. But by default this does absolutely nothing, no logs to stdout, nothing.
You have to add another crate, a so-calling *logging frontend* that accepts logging messages and forward them to some output. `tauri-plugin-log` is such a frontend (with some tauri specific additions).

This design makes *modular logging* a possibility. If you need to debug a problem, getting information from lower level crates can be very helpful. But you as the final consumer remain in control of all the messages.

**Comment by percy507** [comment]
Thank you very much. Your answers are really helpful. 👍👍👍
