### ISSUE TITLE
[window-state][v2] macOS using plugins causes apps to get stuck

### ISSUE THREAD

**Issue by ayangweb** [tauri-apps/plugins-workspace#1918]
demo: https://github.com/ayangweb/test-window-state

macOS video: 

The mouse is always loading, but the screen recorder doesn't record it.

https://github.com/user-attachments/assets/ffeeac64-74e0-4186-95ea-1a3a9a52a219

Windows video:

https://github.com/user-attachments/assets/d6037443-29c0-4826-8886-4de7c838f512

[More demo videos](https://github.com/tauri-apps/plugins-workspace/issues/1916)

**Comment by ayangweb** [comment]
@FabianLars @amrbashir Hey👋, excuse me, remember to read this when you have time!

**Comment by hut36** [comment]
Ran into the same problem. Tried to fix it and this is my investigation so far:

- The problem is triggered by the call to is_maximized() from within restore_state()
- The problem is caused by the call to is_maximized() from WindowEvent::Resized event handler. The tao implementation of is_zoomed() (the counterpart of is_maximized()) for MacOS sets `NSWindowStyleMask::NSTitledWindowMask | NSWindowStyleMask::NSResizableWindowMask` in case of no title and not resizable, which most probably causes event `resized` be emitted.
- this can be verified by setting `windows > decorations` or `windows > resizable` to false in `tauri.conf.json`, and delete `.window-state.json` before running the app.

**Comment by ayangweb** [comment]
I've implemented a simple version on my own for now that runs relatively stable, looking forward to fixing it soon 🌹!

https://github.com/EcoPasteHub/EcoPaste/pull/677

**Comment by hut36** [comment]
Just comment out this line if you want a quick workaround. https://github.com/tauri-apps/plugins-workspace/blob/7e1c17a635f10d69e10ea9f35081a68c71276203/plugins/window-state/src/lib.rs#L475

**Comment by hut36** [comment]
Same reason: https://github.com/tauri-apps/tauri/issues/5812

**Comment by 1111mp** [comment]
Same problem on macos

**Comment by ayangweb** [comment]
@FabianLars @amrbashir Hey 👋, bothering you both, any progress on this issue?

**Comment by FabianLars** [comment]
I looked into it only very very briefly. Maybe it makes sense to disable the is_maximzed check in the plugin for undecorated windows for now. Actually fixing the inner issue may take a while.

**Comment by bstst** [comment]
Exact same issue is happening for me too. Using this window

```
                    .decorations(false)
                    .transparent(true)
                    .resizable(true)
```

`"@tauri-apps/plugin-window-state": "^2.4.0"`
