### ISSUE TITLE
[updater][v2] The app repeatedly upgrades and never gets updated

### ISSUE THREAD

**Issue by ayangweb** [tauri-apps/plugins-workspace#1954]
Hey 👋, In tauri v1 everything updates fine, but in tauri v2 it doesn't! I hope this helps me out, thanks!

MacOS:

https://github.com/user-attachments/assets/7cbd1a3d-4314-420c-8141-04939aeaa866

Windows:

https://github.com/user-attachments/assets/d978f3c2-30c2-4b10-a1ef-0fe02b2cf362

[v0.2.0-beta.3](https://github.com/EcoPasteHub/EcoPaste/releases/tag/v0.2.0-beta.3) 👉 [v0.2.0](https://github.com/EcoPasteHub/EcoPaste/releases/tag/v0.2.0) You can test it out.

`v0.2.0-beta.3` It's already tauri v2.

GitHub Action: https://github.com/EcoPasteHub/EcoPaste/blob/master/.github/workflows/release.yml

Update Component: https://github.com/EcoPasteHub/EcoPaste/blob/1dedc4682e04f365381f79da5a8414920366ef0f/src/components/UpdateApp/index.tsx#L133

tauri config: https://github.com/EcoPasteHub/EcoPaste/blob/1dedc4682e04f365381f79da5a8414920366ef0f/src-tauri/tauri.conf.json#L79

As a final note, my secret and public keys are both from tauri v1, not sure if that has anything to do with it!

**Comment by Legend-Master** [comment]
The callback in `downloadAndInstall` is about the download progress, you need to `await downloadAndInstall` and then `await relaunch()` instead of calling `relaunch` when receiving a `DownloadEvent::Finished`

https://github.com/tauri-apps/plugins-workspace/blob/36207a93f34c45fae506e2df16b0cea82cb56aab/plugins/updater/README.md?plain=1#L75-L83

**Comment by ayangweb** [comment]
<img width="554" alt="image" src="https://github.com/user-attachments/assets/0bbf8961-9529-4f45-98d7-44eb8bf9aefe">

Thanks, it worked 🌹!
