### ISSUE TITLE
[fs] v2 - Add appending to writeFile

### ISSUE THREAD

**Issue by Dan0xE** [tauri-apps/plugins-workspace#2]
Currently its not possible to append to a file, would be nice to have that!

**Comment by NetOpWibby** [comment]
Oh snap, added to Roadmap two weeks ago. Good to know I'll be able to delete this hacky code I'm about to write.

**Comment by FabianLars** [comment]
every issue was added to the roadmap board so don't take this as a "we're working on it". Technically all open issues always were on our roadmap.

That said, i added it in v1 already so i expect it to land here quite quickly (also a somewhat simple thing to contribute since it's basically copy paste now :D )
