### ISSUE TITLE
[sql] No way to close an exsisting connection.

### ISSUE THREAD

**Issue by 4silvertooth** [tauri-apps/plugins-workspace#200]
I didn't find a way to close an existing connection either from rust or script.

**Comment by yankeeinlondon** [comment]
What's the use case you're solving for @4silvertooth? In most use cases keeping an open connection pool between front and backend is desirable but i have no doubt that closing the connection may be a desired state to manually put the connection into (especially for non-Sqlite based DBs). Just looking for some additional context on what you were hoping to achieve.

**Comment by 4silvertooth** [comment]
For desktop environment application can have multiple database files, (a financial application with multiple companies can have individual db file), to switch between these database files it's required to close the previous connection and open a new connection with a different database file.

**Comment by yankeeinlondon** [comment]
I see. Just out of curiosity, is this a regulatory requirement or a
functional goal for better isolation? In either case, I think the ability
to do this makes sense as a feature going forward.

**Comment by 4silvertooth** [comment]
I was evaluating tauri with sqlite plugin for a project. It's not a regulatory requirement, but accountants usually has really large set of company data they work with, so it makes sense to isolate individual company data into seperate db file.

**Comment by alllex** [comment]
I believe this is an essential part of the plugin functionality and it should be supported.

Even for the case of SQLite the connection should be closed properly when it's not needed anymore. Otherwise, SQLite would be forced to leave own temporary files on disk, e.g. when [running in WAL-mode](https://sqlite.org/tempfiles.html#:~:text=2.2.%20Write%2DAhead%20Log%20(WAL)%20Files).
