### ISSUE TITLE
Images in plugin api-docs make vscode weird

### ISSUE THREAD

**Issue by liigo** [tauri-apps/plugins-workspace#2037]
![tauri-plugin-baddoc](https://github.com/user-attachments/assets/d0a0b929-8e95-4028-867a-75e0811e0e50)

**Comment by FabianLars** [comment]
idk if there's a fancy way to only make the image show on docs.rs but even there it looks a bit out of place because virtually no other crate has header images. in other words, imo we should remove the images from the inline docs (keeping them in the readme for cratesio)

Thanks for bringing this to our attention.
