### ISSUE TITLE
[store] Next js support?

### ISSUE THREAD

**Issue by akwanmaroso** [tauri-apps/plugins-workspace#217]
Hi, 

Wanna ensure is this plugin compatible with next.js ? because when I implement it into the next.js app, got this issue 
```js
ReferenceError: window is not defined
```

Thank you

**Comment by FabianLars** [comment]
tldr: Yes it's compatible but needs special handling because of next's SSR context.

This plugin has the same "issue" as all built-in tauri apis. It needs access to the `window` (or sometimes the `navigator`). The problem is that nextjs is SSR-first and there is no `window` in SSR contexts.

Because this plugin uses tauri's `appWindow` it tries to access the `window` on import already so you need to switch to dynamic imports in client-side contexts (for example an onMount useEffect)

btw dynamic imports are these things: `await import('module-name')`

**Comment by akwanmaroso** [comment]
oh, I see, good to know that. 

thank you @FabianLars
