### ISSUE TITLE
[store] How do i get or set from the store in rust?

### ISSUE THREAD

**Issue by sbeckeriv** [tauri-apps/plugins-workspace#224]
Dearest Maintainer, 

I would like to use this store for configuration. The app I am creating has a UI and CLI. I am unsure how I can access the config from rust right now. Any advice would be appreciated.

Thanks for you work on this.
Becker

**Comment by FabianLars** [comment]
plugins generally don't have a rust api (mainly because we couldn't think of a nice design yet), but this plugin uses a plain json file at `app_dir() / store-name` or if you can't use tauri's app_dir api: `config_dir() / bundle-id / store-name`. (config_dir is part of tauri's api and [dirs-next](https://crates.io/crates/dirs-next))

Nothing special about the file itself so you can parse it yourself with [serde_json](https://crates.io/crates/serde_json).

**Comment by sbeckeriv** [comment]
Hello @FabianLars ,

Thank you for your response. I thought that this might be the case. i have seen a few plugins that lack a rust facing interface and I have been confused by this choice.  I was hoping that plugins would offer the same interface to both layers making it easier to code between the two. I misunderstood that this was a built in concept to tauri.  

You give an example but even just providing the loaded data to rust would be a simple start. There are many advantages to having the plugin provide both interfaces. Reading the set/get/clear code I can understand why it is not a simple task. 

I might take a stab at it. If there was an interface trait that a Javascript and Rust store implemented it could be bpassed around by the trait where required. The builder can build for either or.  Maybe the trait logic just handles things like `window.emit(` and is a no op for rust. 

thanks for the reply
Becker

**Comment by FabianLars** [comment]
> i have seen a few plugins that lack a rust facing interface

It's _every_ plugin. 😅 Because of 2 reasons:
1) As i mentioned earlier, we couldn't really think of a one-fits-all approach (that is actually integrated with the plugin system)
2) The main purpose of (community) plugins (not the plugin _system_ itself) is to extend the javascript api with stuff that's either only possible in rust or _should_ be done in rust. From experience most users were/are better off with a completely custom solution once they need/want to do stuff in rust anyway.

**Comment by ash0080** [comment]
It should be relatively convenient to at least allow reading the store in a Rust backend. For example, if I need to perform some heavy tasks, it wouldn't be necessary to first read the settings from the frontend and then send back a portion of the settings to the backend for Rust to process. This approach maybe quite verbose.

**Comment by FabianLars** [comment]
@ash0080 the store plugin has had a rust api for quite a while now. There is a `with_store` method you can use to read&modify the stores that are also exposed to the js side: https://github.com/tauri-apps/plugins-workspace/blob/v1/plugins/store/README.md#usage-from-rust

**Comment by ash0080** [comment]
> @ash0080 the store plugin has had a rust api for quite a while now. There is a `with_store` method you can use to read&modify the stores that are also exposed to the js side: https://github.com/tauri-apps/plugins-workspace/blob/v1/plugins/store/README.md#usage-from-rust

The following may not be pleasant to hear, but I have considered it for a long time and I would like to share my experience.

1. I feel that the person who developed this plugin doesn't actually use it to write apps, which is why the design of this plugin is so difficult to use.

The designer did not consider the initialization on the backend. Although .default() and .defaults() interfaces are provided, they seem more geared towards the JavaScript side. Let me give you an example. Let's say the Rust backend needs to check if the user's permissions have expired during initialization. Shouldn't this be done in the builder.setup() function, and then retrieve this condition when loading on the web side? Moreover, the parameters passed to default() and defaults() are not even a struct, but rather JsonValue... This means that a lot of template code needs to be written to accomplish what should have been a very simple initialization. The two initialization methods I can think of right now are: checking if the store file exists, and if it doesn't, copying a default file using fs::copy; the other method I'll show you is really cumbersome and ugly!
```rust
builder = builder.setup(|app| {
        let default_settings = Settings::default();
        // start --> All of this is garbage code
        let default_json = serde_json::to_string_pretty(&default_settings).unwrap();
        let json_value: Value = serde_json::from_str(&default_json)?;
        let mut defaults = HashMap::new();
        for (k, v) in json_value
            .as_object()
            .unwrap()
        {
            defaults.insert(k.to_string(), v.to_owned());
        }
       // end
        let mut store = StoreBuilder::new(app.app_handle(), SETTINGS_FILE_NAME.parse()?)
            .defaults(defaults)
            .build();
...

```

2. Speaking of with_store, the closure type in the with_store() function is FnOnce(&mut Store<R>) -> Result<T, Error>, which means that all operations, except for insert, delete, and reset, do not satisfy this type... This means that even the simplest get operation requires type conversions... I guess this is probably the main reason why I didn't initially understand how to use this function.

3. It is not possible to work with regular crates like config-rs or figment mainly because the design of this plugin revolves around JSON rather than around structs... It might work fine for lightweight applications that just need Tauri as a renderer using pure JavaScript app.

4. The document is extremely sloppy, and it's hard to understand what it's trying to say.

I apologize if there are any inaccuracies in my statements. In summary, these are some of the struggles and areas of confusion I have encountered while using this plugin.
