### ISSUE TITLE
[store] use `load` method error

### ISSUE THREAD

**Issue by hey-feitian** [tauri-apps/plugins-workspace#227]
When I call `store.load()` after using `store.save()` to disk.

> Failed to deserialize store. Bincode does not support the serde::Deserializer::deserialize_any method

**Comment by jmcartlamy** [comment]
I have the same error. The `store.save()` writes to the disk a file (ex: `.store`) at the following location for macOS: `~/Library/Application Support/bundle-identifier/` with the content I want. But `store.load()` failed with the error described by @hey-feitian.

The issue is located on the following line:
https://github.com/tauri-apps/tauri-plugin-store/blob/cf6c28d50446d480379e1af22aad1ea22b0d887f/src/store.rs#L182

**Comment by FabianLars** [comment]
Yeah bincode can't deserialize into `serde_json::Value` since bincode is not a self-describing format. I guess we have to re-think our approach here.

**Comment by nothingismagick** [comment]
Would this help us?
https://github.com/bincode-org/bincode/issues/425#issuecomment-951631975

**Comment by nothingismagick** [comment]
Or we try out their 2.0.0-rc ?

https://github.com/bincode-org/bincode/releases/tag/v2.0.0-rc.1

**Comment by FabianLars** [comment]
> Would this help us?
I don't think so

> Or we try out their 2.0.0-rc ?
That probably won't help either, but still worth a try.

For reference, the last time(s) they talked about serde_json::Value: https://github.com/bincode-org/bincode/issues/374 and https://github.com/bincode-org/bincode/issues/386
So we probably need to drop bincode (the only alternative that comes to mind would be to serialize to a json string first, but that would defeat the point of bincode too (the resulting file should be the same as if we save the string directly iirc)

**Comment by JonasKruckenberg** [comment]
I just remembered that we use this plugin at work. I checked and it works just fine. This is a bit curious to me, since the error here makes sense. Wouldn't `load()` fail every time regardless of what data the file contains?

Edit: Imo it's okay to just write json as proposed in the PR, I'm just trying to understand this. 
Edit2: Even if bincode is not self describing, shouldn't encoded enums have enough data to correctly deserialize them? And since serde_json::Value is just a glorified enum shouldn't that just work?

**Comment by FabianLars** [comment]
> Wouldn't load() fail every time regardless of what data the file contains?

Well i think so, yeah. It does get triggered on a simple `"test"`, didn't test numbers, but that should behave the same because it always tries to deserialize to `Value`. Idk why it seems to work for you tho, unless you changed the de/serializer functions 🤷 

> Even if bincode is not self describing, shouldn't encoded enums have enough data to correctly deserialize them? And since serde_json::Value is just a glorified enum shouldn't that just work?

The Deserialize implementation of `Value` uses `deserialize_any` (because it wants to be described by the json input, if that makes sense?) which is the actual problem here. If we would re-implement a similar enum with "explicit" deserializers it should work yeah, but not worth it imo.

**Comment by JonasKruckenberg** [comment]
> Well i think so, yeah. It does get triggered on a simple `"test"`, didn't test numbers, but that should behave the same because it always tries to deserialize to `Value`. Idk why it seems to work for you tho, unless you changed the de/serializer functions 🤷

Yeah, had changed the format 🤦🏻‍♂️ nvm
