### ISSUE TITLE
Windows Defender detects ChatGPT.exe as a Trojan

### ISSUE THREAD

**Issue by lencx** [tauri-apps/plugins-workspace#258]
The file from the user screenshot seems to be related to autostart, can you check the issue.
- https://github.com/lencx/ChatGPT/issues/440#issuecomment-1435833340
- https://github.com/lencx/ChatGPT/issues/436

**Comment by FabianLars** [comment]
I don't think this is related to the autostart plugin, the problem started long after you added the plugin. I think it only lists the startup entry because it is technically a file belonging to your program.

Edit: Maybe i'm wrong about the "long after you added the plugin" thing since it does not seem to affect v0.11 yet (only 0.10.3 for me)

**Comment by lencx** [comment]
Thanks for the reply, no unknown dependencies were installed during the application upgrade, this issue appeared suddenly, so is this issue coming from Windows Defender or has Windows Defender changed its detection of Tauri applications?

Correction, I have installed `tauri-plugin-window-state` in v0.11.0.

**Comment by FabianLars** [comment]
> has Windows Defender changed its detection of Tauri applications?

Could be, there are like daily updates to it and its database. It could also because your app got so many users in a short time.

One thing that makes me wonder if this is something really specific to your app, is that so far all false-positives reported `Trojan:Script/Wacatac.H!ml`. I've never seen `Trojan:Win64/Malgent!MSR` in this context before.
Also it's a bit weird that chatgpt 0.11 is seemingly not affected, or at least not yet.

**Comment by lencx** [comment]
Thank you for your response. The awkward thing is, I also don't know how to explain this reason to the user. 😅

**Comment by kurdin** [comment]
@lencx  @FabianLars I just added the `autostart` plugin to my app and quick test with build/release version on Windows 10 indicates the same problem. Right after enabling the `autostart` via Javascript APIs, Windows Defender detects virus/thread and deletes exe file of the app.

![image](https://github.com/tauri-apps/plugins-workspace/assets/6027060/d9d7f4e9-7e38-46bf-a868-fa32a3694d8d)
