### ISSUE TITLE
Mirrors should prepend mirror-only status to the README

### ISSUE THREAD

**Issue by chippers** [tauri-apps/plugins-workspace#267]
If someone stumbles upon a specific plugin mirror without knowing about this repository, it can make it hard to find the right place to contribute.  The sync to mirrors script should probably prepend some information about how that repo is a read-only mirror and for contributions it should link to this repository.

**Comment by FabianLars** [comment]
Personally i'd prefer to keep the sync script as simple as possible (though i'd like to hear @JonasKruckenberg opinion on that, especially since he created that script in the first place).

Do you think it would be enough to change the repo description like we did in the websocket repo <https://github.com/tauri-apps/tauri-plugin-websocket>
![grafik](https://user-images.githubusercontent.com/30730186/223095242-d35c804a-81ae-4397-87ad-60b1e1bb8873.png)
and adding a link to the upstream repo in the [#contributing section](https://github.com/tauri-apps/plugins-workspace/blob/mirror/shared/template/README.md?plain=1#L59) (which would also show up in this repo but whatever)?

**Comment by JonasKruckenberg** [comment]
Yeah I think this is a good idea, maybe we can add a second update-readme script to keep things tidy

**Comment by FabianLars** [comment]
Closing this as i'll try to get rid of the mirrors in v2.
