### ISSUE TITLE
[store] doesn't save my changes

### ISSUE THREAD

**Issue by mhsfh** [tauri-apps/plugins-workspace#42]
Hello everyone, 
thanks for this great plugin.
i'm facing a problem is when i build the app and insert some values when i close the app and re-open it again my changes disappear
the app : https://github.com/mhsfh/Bilal-app

**Edit:**  i removed the plugin from the main branch, i m using it in this branch :
https://github.com/mhsfh/Bilal-app/tree/using-store-plugin

thanks

**Comment by JonasKruckenberg** [comment]
How are you closing the app? Because it will only automatically save changes when the app is closed "regularly" i.e. through the window control buttons or some other UI buttons. If killed using the task manager's (or activity view's) "force stop" buttons or via ctrl+c (or when the device crashes) the plugin will not automatically save changes as the program simply doesn't live long enough to do so.

**Comment by mhsfh** [comment]
@JonasKruckenberg
as it shown [here ](https://github.com/mhsfh/Bilal-app/blob/b471f836619b84d54551cd61c05d45a34763df34/src-tauri/src/main.rs#L33)
```rust
"quit" => {
  std::process::exit(0);
  }
```
this for closing the app from tray 
with what do you suggest to me to replace this line of code so the plugin can save the changes ?
thanks

**Comment by JonasKruckenberg** [comment]
You should use [this method](https://docs.rs/tauri/1.2.3/tauri/struct.AppHandle.html#method.exit) instead, as the description indicates:
> Exits the app. This is the same as [std::process::exit](https://doc.rust-lang.org/nightly/std/process/fn.exit.html), but it performs cleanup on this application.
This method will call the correct before-exit hooks that are required for the plugin to save your state. `std::process::exit` just exits your app immediately
