### ISSUE TITLE
[websocket] Why the plugin of weboskcet api is different to the browser native WebSocket?

### ISSUE THREAD

**Issue by xiatian12345** [tauri-apps/plugins-workspace#605]
why the plugin of websocket api is different to this [https://developer.mozilla.org/en-US/docs/Web/API/WebSocket](url)

**Comment by FabianLars** [comment]
Because tauri plugins are basically just an interface on top of rust (A collection of [tauri commands](https://tauri.app/v1/guides/features/command/) i guess) and reconstructing that same web api with tauri's IPC is a bit tricky. On top of that, the older plugins were often a bit rushed and didn't get the love they deserve yet. We'd like to change that but we have really limited time.
