### ISSUE TITLE
[window-state] plugin overrides minWidth and minHeight config values

### ISSUE THREAD

**Issue by klm-lab** [tauri-apps/plugins-workspace#683]
After plugins init, minWidth and minHeight config in `tauri.config.json` is no longer taken into account. 

```js
tauri::Builder::default()
         .plugin(tauri_plugin_window_state::Builder::default().build()) // <-- init line
         .invoke_handler(tauri::generate_handler![greet])
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
```

If i comment plugin line, config are working.

**Comment by FabianLars** [comment]
So, the reason this happens is because the plugin uses the standard setSize apis which generally ignore the minWH settings.
Usually this isn't really an issue since the user can't resize it smaller than the minWidth/minHeight settings anyway so the plugin can't set height/width smaller than that.

Did you recently change your minHeight/minWidth settings? If so, you may have to reset the plugin's save file. It's inside a folder with the name of your app's bundle.identifier in this folder: https://tauri.app/v1/api/js/path#configdir

I think i'll close this issue for now since it behaves as expected but we'll reconsider if more people have problems with this :)
