### ISSUE TITLE
[websocket] WebSocket server running on localhost doesn't work

### ISSUE THREAD

**Issue by iwan-uschka** [tauri-apps/plugins-workspace#866]
I tried to understand the plugin and run the [example app](https://github.com/tauri-apps/plugins-workspace/tree/v1/plugins/websocket/examples/tauri-app). Maybe i am getting the idea wrong (shipping a WebSocket server within the app itself that other clients can connect to in the same network) or the plugin doesn't work as expected.

So i "forked" the example app (https://github.com/iwan-uschka/tauri-websocket-example-app) and [updated some bits](https://github.com/iwan-uschka/tauri-websocket-example-app/commits/main/) to make it work.

The app starts without any issues. The WebSocket server seems to be up and running at `ws://127.0.0.1:8080` (as defined in [`main.rs`](https://github.com/iwan-uschka/tauri-websocket-example-app/blob/main/src-tauri/src/main.rs#L10C15-L10C29)). The client within the app can establish a connection ([WebSocket `readyState`](https://developer.mozilla.org/en-US/docs/Web/API/WebSocket/readyState) returns `1`). This also applies to other clients from various external browsers and Postman instances.

The problem: sending a message results in an immediate response of the same message at the same client.

<img width="625" alt="Bildschirmfoto 2023-12-30 um 19 44 19" src="https://github.com/tauri-apps/plugins-workspace/assets/2256579/f20fd3ad-1759-41af-b8e8-b613176c00bd">

<img width="832" alt="Bildschirmfoto 2023-12-30 um 19 43 56" src="https://github.com/tauri-apps/plugins-workspace/assets/2256579/8cc6957b-3aac-4003-86a1-9d345c855ebe">

The rest of the clients don't receive anything.

What am i doing wrong?

**Comment by iwan-uschka** [comment]
Everything works as expected (sending & receiving) after connecting to a remote WebSocket server like `wss://socketsbay.com/wss/v2/1/demo/` (https://socketsbay.com/test-websockets) instead of the "internal" server running at `ws://127.0.0.1:8080`.

**Comment by FabianLars** [comment]
So i couldn't 100% follow what you're doing (but i'm on a run so it's my bad) but the plugin is a websocket _client_, not a server, for use cases where the browser native websocket client doesn't work (cors or mixed content for example). It sounds like you're focusing on the example server which is just used to showcase the client plugin.

I hope this helps you figure it out, if not i'm back in 1-2 days :)

**Comment by iwan-uschka** [comment]
Thanks for getting back on this one. I am still wondering why i am able to connect to `ws://127.0.0.1:8080` (WebSocket server inside the Tauri app) with different WebSocket clients running in and outside the Tauri app without enabling all these clients to send and receive all messages except their own. The client's [readyState](https://developer.mozilla.org/en-US/docs/Web/API/WebSocket/readyState) works btw. It's set to `3` in all clients after shutting down the Tauri app.

This is about a side project i am working on. Nothing crucial. No pressure 🙃

**Comment by FabianLars** [comment]
> The rest of the clients don't receive anything.

Doesn't this mean it did receive the same message it sent?
![grafik](https://github.com/tauri-apps/plugins-workspace/assets/30730186/18806eb8-be37-4a76-b10b-934e29ca8f2d)

Cause that's what the example server does, it simply returns what it got, or in other words:

> The problem: sending a message results in an immediate response of the same message at the same client.

That's expected behavior.

----

The server in the example app only returns the message it got, to the same client it got it from, nothing else. https://github.com/iwan-uschka/tauri-websocket-example-app/blob/main/src-tauri/src/main.rs#L26-L29

The client == the websocket plugin is just an alternative to postman or the browser's WebSocket api. So all clients should show the same behavior (as long as they can connect to the ws server without mixed content errors (if the client runs in a secure context).

In the example the html gets updated with the response the plugin client got from the server, it does not show anything from other clients.

----

If that also doesn't help you in any way please try to explain your problem/question differently, maybe i'm just really dense right now 😅

**Comment by iwan-uschka** [comment]
Now i got it. Due to my lack of knowledge about Rust i am unfortunately not able to understand what's going on in the example app and i simply misunderstood what the plugin's mainly about. I wasn't aware of the "poor" WebSocket server implementation. I thought the example app would provide a fully featured WebSocket server based on the plugin. Turns out i was wrong 🙃 Thanks for clarifying.

**Comment by bugCats** [comment]
websocket如果使用`127.0.0.1`或者`localhost`，可以正常工作。

但是如果使用远程地址，例如`wss://remote.mydomain`，则会抛出`POST http://ipc.localhost/plugin%3Awebsocket%7Cconnect net::ERR_CONNECTION_REFUSED`异常！

我修改`capabilities/default.json`文件：
```
{
  "identifier": "default",
  "remote": {
    "urls": [
      "https://remote.mydomain", 
      "wss://remote.mydomain"
    ]
  },
  "permissions": [
    "websocket:default",
    "websocket:allow-connect",
    "websocket:allow-send"
  ]
}
```

但似乎并没有效果。

请问一下要如何配置，可以使websocket客户端访问远程服务器？
