### ISSUE TITLE
[window-state] App window stuck on non existing monitor

### ISSUE THREAD

**Issue by erikpa1** [tauri-apps/plugins-workspace#97]
Hi, I was working with my secondary monitor (also in windows it was as secondary monitr), went on trip turned on app and here I have problem I can't get tauri window back from non existing monitor...

![image](https://user-images.githubusercontent.com/19526670/213092883-42ad2f67-b8e8-4776-9b95-6798842f99c5.png)

**Comment by FabianLars** [comment]
You can move it back by focusing the window and using the arrow keys while holding the windows key. Or deleting the .window-state file in `AppData/Roaming/your-bundleid/` should help too.

To prevent this bug you should use the plugin from git instead of the published crate
```toml
tauri-plugin-window-state = { git = "https://github.com/tauri-apps/plugins-workspace" }
```
(run `cargo update` in your src-tauri dir afterwards)
